lhbs/api/routes.py
from flask import Blueprint, jsonify, request, redirect, flash, url_for
from flask_login import login_required, current_user
from lhbs.models import Booking
from lhbs import db
import datetime

api = Blueprint('api', __name__)

all_lecture_halls = {1: "Lecture Hall 1", 2: "Lecture Hall 2", 3: "Lecture Hall 3", 4: "Lecture Hall 4",
                     5: "Lecture Hall 5", 6: "Lecture Hall 6", 7: "Lecture Hall 7", 8: "Lecture Hall 8",
                     9: "Lecture Hall 9", 10: "Lecture Hall 10", 11: "Lecture Hall 11", 12: "Lecture Hall 12",
                     13: "Lecture Hall 13", 14: "Lecture Hall 14", 15: "Lecture Hall 15", 16: "Lecture Hall 16"}

# slot for 12 hours hence 12*60*60 seconds
total_time = 43200


@api.route("/dates")
def show_dates_api():
    start_date = datetime.datetime.now().date()
    all_dates = []
    for i in range(1, 31):
        next_date = start_date + datetime.timedelta(days=i)
        all_dates.append(next_date)
    
    dates = []
    for check_date in all_dates:
        check_date_data = Booking.query.filter_by(date=check_date).all()
        check_date_total_time = 0
        for check_date_time_data in check_date_data:
            check_date_start_time = check_date_time_data.start_time
            check_date_end_time = check_date_time_data.end_time
            check_date_interval_time = int((datetime.datetime.combine(datetime.date.today(), check_date_end_time)
                                            - datetime.datetime.combine(datetime.date.today(), check_date_start_time)).
                                           total_seconds())
            check_date_total_time += check_date_interval_time
        if check_date_total_time == len(all_lecture_halls) * total_time:
            is_available = False
        else:
            is_available = True
        dates.append([str(check_date), check_date.strftime("%A"), is_available])
    dates_api_data = {"dates": dates}
    return jsonify(dates_api_data)


@api.route("/dates/<string:specific_date>")
def show_lecture_halls_api(specific_date):
    specific_date_date_obj = datetime.datetime.strptime(specific_date, "%Y-%m-%d").date()
    lecture_halls = []
    for lecture_hall_key, lecture_hall_value in all_lecture_halls.items():
        lecture_hall_data = Booking.query.filter_by(date=specific_date_date_obj,
                                                 lecture_hall=lecture_hall_key).all()
        lecture_hall_total_time = 0
        for lecture_hall_time_data in lecture_hall_data:
            lecture_hall_start_time = lecture_hall_time_data.start_time
            lecture_hall_end_time = lecture_hall_time_data.end_time
            lecture_hall_interval_time = int((datetime.datetime.combine(datetime.date.today(), lecture_hall_end_time)
                                              - datetime.datetime.combine(datetime.date.today(),
                                                                          lecture_hall_start_time)).total_seconds())
            lecture_hall_total_time += lecture_hall_interval_time
        if lecture_hall_total_time == total_time:
            is_available = False
        else:
            is_available = True
        lecture_halls.append([lecture_hall_key, lecture_hall_value, is_available])
    lecture_halls_api_data = {"lecture_halls": lecture_halls}
    return jsonify(lecture_halls_api_data)


@api.route("/dates/<string:specific_date>/<int:lecture_hall>")
def show_time_slot_api(specific_date, lecture_hall):
    booked_time_slots = []
    specific_date_date_obj = datetime.datetime.strptime(specific_date, "%Y-%m-%d").date()
    time_slot_data = Booking.query.filter_by(date=specific_date_date_obj, lecture_hall=lecture_hall).all()
    for check_time_slot_data in time_slot_data:
        time_slot_start_time = check_time_slot_data.start_time
        time_slot_end_time = check_time_slot_data.end_time
        booked_time_slots.append([str(time_slot_start_time), str(time_slot_end_time),
                                 time_slot_start_time.strftime("%I:%M %p"),
                                  time_slot_end_time.strftime("%I:%M %p"), False])
    booked_time_slots.sort(key=lambda x: int(x[0].split(":")[0])*60 + int(x[0].split(":")[1]))
    time_slots = []
    if booked_time_slots:
        first = ["08:00:00", booked_time_slots[0][0], "08:00 AM", booked_time_slots[0][2], True]
        if first[0] == first[1]:
            pass
        else:
            time_slots.append(first)
        for i in range(len(booked_time_slots) - 1):
            time_slots.append(booked_time_slots[i])
            available_slot = [booked_time_slots[i][1], booked_time_slots[i + 1][0], booked_time_slots[i][3],
                              booked_time_slots[i + 1][2], True]
            time_slots.append(available_slot)
        time_slots.append(booked_time_slots[-1])
        last = [booked_time_slots[-1][1], "20:00:00", booked_time_slots[-1][3], "08:00 PM", True]
        if last[0] == last[1]:
            pass
        else:
            time_slots.append(last)
    else:
        time_slots.append(["08:00:00", "20:00:00", "08:00 AM", "08:00 PM", True])
    time_slots.sort(key=lambda x: x[4], reverse=True)
    time_slot_api_data = {"time_slots": time_slots}
    return jsonify(time_slot_api_data)


@api.route("/book-slot", methods=["GET", "POST"])
@login_required
def book_time_slot_api():
    booked_date = request.form.get("date")
    booked_date_date_obj = datetime.datetime.strptime(booked_date, "%Y-%m-%d").date()
    booked_lecture_hall = request.form.get("lectureHall")
    booked_lecture_hall_int_obj = int(booked_lecture_hall)
    booked_start_time = request.form.get("startTimeValue")
    booked_start_time_time_obj = datetime.datetime.strptime(booked_start_time, "%H:%M:%S").time()
    booked_end_time = request.form.get("endTimeValue")
    booked_end_time_time_obj = datetime.datetime.strptime(booked_end_time, "%H:%M:%S").time()
    purpose = request.form.get("purpose")
    if booked_end_time_time_obj > booked_start_time_time_obj:
        check_data = Booking.query.filter(Booking.date == booked_date_date_obj,
                                          Booking.lecture_hall == booked_lecture_hall_int_obj,
                                          Booking.start_time <= booked_start_time_time_obj,
                                          Booking.end_time >= booked_end_time_time_obj).count()
        if check_data:
            flash("Somebody already booked between these time slots", "danger")
            return redirect(url_for("view.home_page"))
        add_data_row = Booking(date=booked_date_date_obj,
                               lecture_hall=booked_lecture_hall_int_obj,
                               start_time=booked_start_time_time_obj, end_time=booked_end_time_time_obj,
                               customer=current_user, purpose=purpose)
        db.session.add(add_data_row)
        db.session.commit()
        flash("Time slot has been booked", "success")
    else:
        flash("Start time must be greater than end time", "danger")
    return redirect(url_for("view.home_page"))


# @api.route("/justToCheck")
# def just_to_check_api():
#     booked_date = "2021-10-11"
#     booked_date_date_obj = datetime.datetime.strptime(booked_date, "%Y-%m-%d").date()
#     booked_lecture_hall_int_obj = 1
#     booked_start_time = "16:00:00.000000"
#     booked_start_time_time_obj = datetime.datetime.strptime(booked_start_time, "%H:%M:%S.%f").time()
#     print(booked_start_time_time_obj)
#     booked_end_time = "18:00:00.000000"
#     booked_end_time_time_obj = datetime.datetime.strptime(booked_end_time, "%H:%M:%S.%f").time()
#     print(booked_end_time_time_obj)
#     check_data = Booking.query.filter(Booking.date == booked_date_date_obj,
#                                    Booking.lecture_hall == booked_lecture_hall_int_obj,
#                                    Booking.start_time <= booked_start_time_time_obj,
#                                    Booking.end_time >= booked_end_time_time_obj).count()
#     check_data_date = check_data.date
#     return jsonify(check_data_date)

lhbs/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from lhbs import db, bcrypt
from lhbs.models import User, Booking
from lhbs.users.forms import (RegistrationForm, LoginForm)


users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('view.home_page'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! Please confirm your email first before log in', 'info')
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('view.home_page'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash('You are now logged in!', 'success')
            return redirect(url_for('view.home_page'))
        else:
            flash("Login unsuccessful please check email and password", "danger")
    return render_template('login.html', title='Login', form=form)


@login_required
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('view.home_page'))

lhbs/view/routes.py
from flask import render_template, Blueprint
from flask_login import current_user, login_required
from lhbs import db
from lhbs.models import Booking
import datetime



view = Blueprint('view', __name__)


@view.route("/")
def home_page():
    return render_template('index.html')


@login_required
@view.route("/user-booking")
def user_booking():
    current_date_time = datetime.datetime.now()
    all_bookings = Booking.query.filter(Booking.user_id == current_user.id).all()
    past_bookings = []
    future_bookings = []
    for booking in all_bookings:
        booking_date = booking.date
        booking_end_time = booking.end_time
        booking_date_time = datetime.datetime.combine(booking_date, booking_end_time)
        if booking_date_time > current_date_time:
            future_bookings.append(booking)
        else:
            past_bookings.append(booking)
    return render_template('user_booking.html', past_bookings=past_bookings, future_bookings=future_bookings)

lhbs/templates/index.html
{% extends 'layout.html' %}

{% block content %}

<form action="{{ url_for('api.book_time_slot_api') }}" method="POST">

    <div class="form-row justify-content-center" style="width:800px; margin:0 auto;">
        <h3 class="text-muted text-center mb-4 mt-4">Lecture Hall Booking System</h3>
    </div>

    <div class="form-row justify-content-center mb-2" style="width:800px; margin:0 auto;">
        <div class="form-group col-md-4">
          <select class="form-control" name="date" id="bookedDate" onchange="changeDateFunc()"></select>
        </div>
        <div class="form-group col-md-4">
          <select class="form-control" name="lectureHall" id="bookedLectureHall" onchange="changeLectureHallFunc()">
            <option disabled selected>Lecture Halls</option>
          </select>
        </div>
        <div class="form-group col-md-4">
          <select class="form-control" name="TimeSlot" id="bookedTimeSlot" onchange="changeTimeSlotFunc()">
            <option disabled selected>Time Slots</option>
          </select>
        </div>
    </div>

    <div class="form-row mb-4" style="width:800px; margin:0 auto;">
        <label for="startTime">Start Time</label>
        <input type="range" class="form-control-range" step="5" id="startTime" disabled
               oninput=changeStartTimeInputFunc()>
        <br />
        <span id="startTimeValue"></span>
        <input type="hidden" name="startTimeValue" id="startTimeOutputValue">
    </div>

    <div class="form-row mb-4" style="width:800px; margin:0 auto;">
        <label for="endTime">End Time</label>
        <input type="range" class="form-control-range" step="5" id="endTime" disabled
               oninput=changeEndTimeInputFunc()>
        <br />
        <span id="endTimeValue"></span>
        <input type="hidden" name="endTimeValue" id="endTimeOutputValue">
    </div>

    <div class="form-row mb-4" style="width:800px; margin:0 auto;">
        <label for="purpose">Purpose</label>
        <textarea name="purpose" class="form-control" id="purpose" rows="3"></textarea>
    </div>

    <div class="form-row justify-content-center" style="width:800px; margin:0 auto;">
        <button class="btn btn-primary btn-lg" type="submit" disabled id="bookSlot">Book</button>
    </div>

</form>

<script src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock content %}

lhbs/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% if title %}
        <title>LHBS-{{ title }}</title>
    {% else %}
        <title>LHBS</title>
    {% endif %}
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
            aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggle">
      <div class="navbar-nav mr-auto">
        <a class="nav-item nav-link active" href="{{ url_for('view.home_page') }}">Home</a>
      </div>
      <div class="navbar-nav">
        {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
          <a class="nav-item nav-link" href="{{ url_for('view.user_booking') }}">Bookings</a>
        {% else %}
          <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
          <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <div class="mt-2" style="width:800px; margin:0 auto;">
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
  {% endwith %}
  </div>
  {% block content %}{% endblock %}


</body>
</html>

lhbs/templates/login.html
{% extends 'layout.html' %}

{% block content %}
<div class="mt-2" style="width:800px; margin:0 auto;">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="#">Forget Password? </a>
                </small>
                <small class="text-muted ml-2">
                    <a href="#">Confirm Email? </a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account?<a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
</div>
{% endblock content %}

lhbs/templates/register.html
{% extends 'layout.html' %}

{% block content %}
<div class="mt-2" style="width:800px; margin:0 auto;">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
        </div>
        <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account?<a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
</div>
{% endblock content %}

lhbs/templates/user_booking.html
{% extends 'layout.html' %}

{% block content %}
<div style="width:800px; margin:0 auto;">
    <label for="futureBookings">{{ current_user.username }}'s Upcoming Bookings</label>
    <table class="table" id="futureBookings">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Lecture Hall</th>
          <th scope="col">Start Time</th>
          <th scope="col">End Time</th>
        </tr>
      </thead>
      <tbody>
      {% for future_booking in future_bookings %}
      <tr>
          <th scope="row">{{ future_booking.date }}</th>
          <td>{{ future_booking.lecture_hall }}</td>
          <td>{{ future_booking.start_time }}</td>
          <td>{{ future_booking.end_time }}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
</div>
<div style="width:800px; margin:0 auto;">
    <label for="pastBookings">{{ current_user.username }}'s Past Bookings</label>
    <table class="table" id="pastBookings">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Lecture Hall</th>
          <th scope="col">Start Time</th>
          <th scope="col">End Time</th>
        </tr>
      </thead>
      <tbody>
      {% for past_booking in past_bookings %}
      <tr>
          <th scope="row">{{ past_booking.date }}</th>
          <td>{{ past_booking.lecture_hall }}</td>
          <td>{{ past_booking.start_time }}</td>
          <td>{{ past_booking.end_time }}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
</div>
{% endblock content %}